name: Submit Pull Request

on:
  create:

jobs:
  SubmitPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Submit Pul Request
        uses: shimewtr/submit_pull_request@master
        env:
          GITHUB_ACCESS_TOKEN: ${{secrets.github_token}}
          LABEL: WIP
